### ISSUE TITLE
request for support of `optparse-applicative` 0.18.*

### ISSUE THREAD

**Issue by peterbecich** [kowainik/extensions#100]
Upper bound is currently `< 0.18`

https://hackage.haskell.org/package/optparse-applicative

This will make it easier to build the library with Nix.  Thank you

**Comment by tomjaguarpaw** [comment]
Resolved by: https://github.com/kowainik/extensions/pull/101

Package revision -r5: https://hackage.haskell.org/package/extensions-0.1.0.2/revisions/
