### ISSUE TITLE
Support PolymorphicComponents

### ISSUE THREAD

**Issue by jan-christiansen** [kowainik/extensions#104]
This is a minor issue, but when processing a couple of Haskell projects from GitHub I failed parsing a module from `haskell/parsec` because https://github.com/haskell/parsec/blob/783376aa67171130fe3e5d31deff150039615f35/src/Text/Parsec/Token.hs#L2 uses the language extension `PolymorphicComponents`. While https://kowainik.github.io/posts/extensions#stranger-things states that it is a Cabal synonym, it looks like GHC accepts this extension as well, although it is not listed on https://downloads.haskell.org/ghc/9.4.8/docs/users_guide/exts/table.html?highlight=extensions.

I am wondering, whether `PolymorphicComponents` should be defined as a synonym for `RankNTypes` in the extensions parser. If so, I am happy to create a small pull request.

PS: **Thanks very much** for creating this library in the first place. It helped me a lot!

**Comment by tomjaguarpaw** [comment]
I'd be happy to take a PR for that.

----

> PS: Thanks very much for creating this library in the first place. It helped me a lot!

(I'm not the creator myself, just a maintainer, but I'm glad to hear the library has helped you. I'm also sure the original creators will be pleased to hear your thanks too, because there is very little gratitude for open source software going around!)
