### ISSUE TITLE
Handle nested comments in pragma parser

### ISSUE THREAD

**Issue by jan-christiansen** [kowainik/extensions#107]
The pragma parser is currently not able to parse nested comments. For example, [`ndmitchell/hlint`](https://github.com/ndmitchell/hlint) contains modules with nested comments, for example https://github.com/ndmitchell/hlint/blob/ad9a1f8485eb34d40a59cc0bd1457d03fbffd50d/src/Hint/Bracket.hs#L5.

If this is of any interest, I will create a pull request that extends the parser to handle nested comments.

**Comment by tomjaguarpaw** [comment]
Yes, seems fine, thanks!
