### ISSUE TITLE
Track usages of 'Safe' family of language extensions

### ISSUE THREAD

**Issue by chshersh** [kowainik/extensions#38]
Language extensions `Safe`, `Unsafe` and `Trustworthy` are special, because:

1. They are parsed by both Cabal and GHC.
2. But they don't have a corresponding constructor of the [GHC `Extension`](http://hackage.haskell.org/package/ghc-boot-th-8.8.1/docs/GHC-LanguageExtensions-Type.html#t:Extension). Even though they are specified using the `{-# LANGUAGE #-}` pragma, they are not recognized as extensions. They are stored in [`DynFlags`](https://hackage.haskell.org/package/ghc-8.6.5/docs/DynFlags.html#t:DynFlags) as the `safeHaskell` field of type [`SafeHaskellMode`](https://hackage.haskell.org/package/ghc-8.6.5/docs/DynFlags.html#t:SafeHaskellMode).
3. They also don't follow the `No` scheme of disabling/enabling extensions.

It would be nice to report these extensions as used, but it's not clear how to model them as data types. Current behaviour: they are ignored during parsing.

**Comment by vrom911** [comment]
Great summary, @chshersh !

From what you wrote I see that it can be `Maybe SafeHaskellExtension` and returned it along with the list of standard extensions. I see also that these three extensions are mutually exclusive, so `Maybe` seems like a possible solution.
