### ISSUE TITLE
New release on Hackage?

### ISSUE THREAD

**Issue by bitc** [kowainik/extensions#72]
Hi, there have been a few fixes on the main git branch, that have not yet been released in a version on Hackage. These would be useful to have

Thank you

**Comment by chshersh** [comment]
@bitc Is there a reason to have a Hackage release now? I see that the latest code change that actually affects the behaviour and compilation of the library has already been published to Hackage.

**Comment by bitc** [comment]
My issue is that extensions-0.0.0.1 currently on Hackage is incompatible with optparse-applicative 0.16 (this issue has been fixed in master branch in 3960e8fa3d80f8ad8a0dc053776ca76f51076492).

You could do a package revision on Hackage to fix this instead of releasing a new version. In any case, this is not critical for me and I am happy to patiently wait for the next version.

Thank you

**Comment by tomjaguarpaw** [comment]
I guess this is fixed by https://hackage.haskell.org/package/extensions-0.1.0.1, if not an earlier release. Please feel free to reopen if there's still a problem and/or I've misunderstood.
