### ISSUE TITLE
Support GHC 9.2

### ISSUE THREAD

**Issue by chshersh** [kowainik/extensions#74]
Created a separate issue for GHC 9.0 (#73) and GHC 9.2. We use GHC API and Cabal API so some amount of non-trivial changes is required to make this library support newer GHC versions.

**Comment by emberdart** [comment]
I'm getting:

```
src/Extensions/Types.hs:164:31: error:
    • Overlapping instances for Ord Extension
        arising from the first field of ‘On’ (type ‘Extension’)
      Matching instances:
        instance [safe] Ord Extension
          -- Defined in ‘GHC.LanguageExtensions.Type’
        instance Ord Extension -- Defined at src/Extensions/Types.hs:270:1
    • When deriving the instance for (Ord OnOffExtension)
    |
164 |     deriving stock (Show, Eq, Ord)
```

on 9.2 at the moment.

**Comment by ulidtko** [comment]
Same error here — but on GHC **9.0.2**. The library `ghc-boot-th` is also version 9.0.2, of course.

The error message refers to line 270:
https://github.com/kowainik/extensions/blob/8776ca0ba7347f51f38fdc7e24ff04d002ea7167/src/Extensions/Types.hs#L269-L270

I guess GHC has added the Ord instance, and so the orphan in this package now creates overlap. The source refers to https://gitlab.haskell.org/ghc/ghc/-/merge_requests/2707

The orphan will probably need `#if __GLASGOW_HASKELL__ < 900` CPP :unamused: 
Or alternatively :thinking: perhaps with cabal mixin compat sublibrary? A-la `relude`, with `if impl(ghc < 9.0.0)`.
Up to @chshersh to decide; for my application, a patch will suffice. HTH

**Comment by tomjaguarpaw** [comment]
This makes it compile all the way from 8.10 to 9.4. I haven't tested it and I don't know if it's correct. It has the downside of requiring Cabal 3.6.

https://github.com/kowainik/extensions/compare/main...tomjaguarpaw:extensions:9.4

**Comment by emberdart** [comment]
I just tested and looks like the test suite fails with:

```

Failures:

  test/Test/Extensions/Types.hs:52:5: 
  1) OnOffExtension tests, Property tests, read . show ≡ Just
         ✗ <interactive> failed at test/Test/Extensions/Types.hs:52:5
           after 2 tests and 1 shrink.
         
              ┏━━ test/Test/Extensions/Types.hs ━━━
           49 ┃ roundtripProperty :: PropertyT IO ()
           50 ┃ roundtripProperty = hedgehog $ do
           51 ┃     onOffExtension <- forAll genOnOffExtension
              ┃     │ On RecordPuns
           52 ┃     tripping
              ┃     ^^^^^^^^
              ┃     │ ━━━ Intermediate ━━━
              ┃     │ "RecordPuns"
              ┃     │ ━━━ - Original) (+ Roundtrip ━━━
              ┃     │ - Just (On RecordPuns)
              ┃     │ + Nothing
           53 ┃         onOffExtension
           54 ┃         showOnOffExtension
           55 ┃         (readOnOffExtension . Text.unpack)
         
           This failure can be reproduced by running:
           > recheck (Size 1) (Seed 11313789858664565033 982094751906803891) <property>
         

  To rerun use: --match "/OnOffExtension tests/Property tests/read . show \8801 Just/"

Randomized with seed 1111796519

Finished in 0.3289 seconds
89 examples, 1 failure
Test suite extensions-test: FAIL
```

on 9.2.4

**Comment by tomjaguarpaw** [comment]
Thanks for checking that. I've pushed a fixed version. Could you check it too?

**Comment by emberdart** [comment]
This seems much better now, thanks!

**Comment by emberdart** [comment]
I think I need to tell ghc 9.0.2 to update the version of cabal in use when I compile it for that version of ghc, though...

**Comment by emberdart** [comment]
Wait, can one even do that? I think I may need to give up trying on 9.0.2, it's probably pointless.

**Comment by tomjaguarpaw** [comment]
Are you seeing a problem with 9.0.2? Can you paste the error message, if so?

**Comment by emberdart** [comment]
Yeah it's probably that 9.0.2 is just using an older Cabal:

```
ghc902: [3 of 5] Compiling Extensions.Cabal
ghc902: 
ghc902: src/Extensions/Cabal.hs:44:1: error:
ghc902:     Could not find module ‘Distribution.Utils.Path’
ghc902:     Perhaps you meant
ghc902:       Distribution.Utils.IOData (from Cabal-3.4.1.0)
ghc902:       Distribution.Utils.MD5 (from Cabal-3.4.1.0)
ghc902:       Distribution.Utils.Base62
ghc902:     Use -v (or `:set -v` in ghci) to see a list of the files searched for.
ghc902:    |
ghc902: 44 | import Distribution.Utils.Path (getSymbolicPath)
ghc902:    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ghc902: error: builder for '/nix/store/nfwc74dcvv4pnh2j12rvz3hrwhmlc55y-extensions-0.0.0.1.drv' failed with exit code 1;
ghc902:        last 10 log lines:
ghc902:        > src/Extensions/Cabal.hs:44:1: error:
ghc902:        >     Could not find module ‘Distribution.Utils.Path’
ghc902:        >     Perhaps you meant
ghc902:        >       Distribution.Utils.IOData (from Cabal-3.4.1.0)
ghc902:        >       Distribution.Utils.MD5 (from Cabal-3.4.1.0)
ghc902:        >       Distribution.Utils.Base62
ghc902:        >     Use -v (or `:set -v` in ghci) to see a list of the files searched for.
ghc902:        >    |
ghc902:        > 44 | import Distribution.Utils.Path (getSymbolicPath)
```

**Comment by tomjaguarpaw** [comment]
That's weird, because cabal is specified in `extensions.cabal` as `Cabal ^>= 3.6`, and [that module does exist in 3.6](https://hackage.haskell.org/package/Cabal-3.6.0.0/docs/Distribution-Utils-Path.html).

**Comment by emberdart** [comment]
Ah, well must be nix overriding 9.0.2 to use 3.4 for some reason.

**Comment by tomjaguarpaw** [comment]
Oh I see. If you're using Nix then I'm afraid I have no idea how to help!

**Comment by emberdart** [comment]
The rest seems fine though, thanks! If you get no reply then I think you'll be able to take over the hackage package.
