### ISSUE TITLE
request for `hspec-hedgehog` dependency bump

### ISSUE THREAD

**Issue by peterbecich** [kowainik/extensions#91]
```
, hspec-hedgehog ^>= 0.0.1
```                     

Can this be changed to support `0.1.*` ? https://hackage.haskell.org/package/hspec-hedgehog
Thank you

**Comment by tomjaguarpaw** [comment]
Hackage revision published: https://hackage.haskell.org/package/extensions-0.1.0.1/revisions/

**Comment by peterbecich** [comment]
Thanks
